name: Docker Image CI

on:
  push:
    branches: 
      - master
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - run: echo ::set-output name=tag_name::$(awk -F ":" 'NR==1{print $2}' Dockerfile)
      id: tag_name_step
    - uses: anothrNick/github-tag-action@1.30.0
      env:
        CUSTOM_TAG: ${{ steps.tag_name_step.tag_name }} 
    #  docker build . --file Dockerfile --tag apache-php-web:$(awk -F ":" 'NR==1{print $2}' Dockerfile)
